### ISSUE TITLE
Sinn dieser Erweiterung

### ISSUE THREAD

**Issue by Olli** [plakart/contao-plakart-connector-bundle#2]
Hi,
ich frage mich gerade über den Sinn der Erweiterung ... es wird ja nur die Contao Version ausgegeben.
Das ist alles über den Contao Manager über die REST API abrufbar ... nur so falls das nicht so bekannt ist :)

**Comment by jaynoe** [comment]
Die Erweiterung dient intern in unserer Agentur als Hilfsmittel - sowohl für Contao-Installationen mit dem Contao-Manager als auch ohne.
